format = """
[╭─](#fff)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260)\


$fill\

[](fg:#212736)\

$nodejs\
$rust\
$golang\
$c\
$cpp\
$kotlin\
$gradle\
$java\
$docker_context\
[](fg:#1d2230 bg:#212736)\
$time\
$cmd_duration
╰─$character"""

[fill]
symbol = "·"

[line_break]
disabled = true
[directory]
style = "fg:#212736 bg:#769ff0"
format = "[ $path ]($style)"
truncate_to_repo = false
use_os_path_sep = false
truncation_length = -1
fish_style_pwd_dir_length = 1

[directory.substitutions]
"E:/" = "/e/"
"D:/" = "/d/"
"C:/" = "/c/"

[cmd_duration]
min_time = 500
format = '[[](fg:#212736 bg:#1d2230)[  $duration ](fg:#769ff0 bg:#212736)]($style)'
show_milliseconds = true

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[cpp]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = " "
format = '[[ $symbol $context ](fg:#769ff0 bg:#212736)]($style)'

[gradle]
symbol=""
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[kotlin]
symbol = ''
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = " "
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
format = '[[ $time ](fg:#a0a9cb bg:#1d2230)]($style)'
